name: Builds

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm i
      - name: Compile for Distribution
        run: |
          npm run compile
      - name: Commit Release Version
        run: |
          git config user.name "AutoBuild"
          git config user.email "autobuild@doctor-internet.dev"
          git add --all
          git commit -m "chore(build): Compiled Code for Distribution"
          git push -u origin release
      - name: Build Release
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
